Topic1
mauriciogbl/startup pull request #2
Opened 2016-10-11 21:02 UTC by mauriciogbl

2016-10-12 13:21 UTC, afiorenza requested changes
Well done! just a few changes

2016-10-12 13:21 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +<body onload="setTimeout(eventFade, 1000);">
This is okey, but you could try to just call the event here and move the setTimeout to the function

2016-10-12 13:21 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +   <script type="text/javascript">
You could move this to the js file

2016-10-12 13:21 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +// if (xhttp.readyState === XMLHttpRequest.DONE)
If you are not going to use this code you could delete it

2016-10-12 13:21 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +function eventOnClick(){
eventOnClick doesn't make sense on what the method do. This could be handleJokeButtonClick

2016-10-12 13:21 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +       if (xhttp.readyState === XMLHttpRequest.DONE) {
It is a good practice to leave a break line between the if block and the line above

2016-10-12 13:21 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +  function resolve(xhttp) {
It is a good practice to leave a break line between the function declaration and the line above

2016-10-12 13:21 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +    document.getElementById("sectionHidden").style.backgroundColor = "red";;
Extra ; here

2016-10-12 13:21 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +function eventRequestReusable(object, resolve, reject) {
Well done this function, but the object should be config. Also you could pass the http method too.

2016-10-12 17:02 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +       if (xhttp.readyState === XMLHttpRequest.DONE) {
if 
(xhttp.readyState === XMLHttpRequest.DONE) {

like that?

2016-10-12 17:39 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +function eventRequestReusable(object, resolve, reject) {
I couldn't change name 'object' for 'config', the function stopped working when i did it.

2016-10-12 18:23 UTC, afiorenza requested changes

2016-10-12 18:23 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +      var response = JSON.parse(event.target.response);
This is going to brake if the request status is not done, you shouldn't do this

2016-10-12 18:23 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +  <button type="button" name="XMLHttpRequest" onclick="eventRequest()" class="buttons" id="buttonSection">XMLHttpRequest</button>
Id should be unique

2016-10-12 18:23 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +function eventRequestReusable(object, resolve, reject) {
Well, try another name

2016-10-12 18:23 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +             document.getElementById("buttonSection").innerHTML  = xhttp.responseText.value.joke;
Why are you doing this?

2016-10-12 18:23 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +    console.log(xhttp.responseText);
Avoid leaving console.log's

2016-10-13 20:51 UTC, afiorenza requested changes
Good job but some changes needed

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exercise12.html
> +   </head>
Check indentation here

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exercise12.html
> +      <th class="tableTH">Firstname</th>
This data should be in the array too

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exercise12.html
> +  <button onclick="importMatrixToDOM(matrix)" id="importMatrixButton" type="buttonImportMatrix" name="buttonImportMatrix">Import</button>
Type `buttonImportMatrix` doesn't exist. This are the current button types http://www.w3schools.com/tags/att_button_type.asp

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exercise12.js
> +    console.log(matrix);
Remember to remove the console.log's before commit

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exercise12.js
> +    matrix = [
You can directly return the matrix

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exercise12.js
> +      var trNode = document.createElement("tr");
Remove all variable declarations outside the loop

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exercise12.js
> +      document.getElementById("dataTable").appendChild(trNode);
You are getting this element several times. Store it in a variable.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.css
> +    width: 100%;
Alpha order css rules.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.css
> +.hiddenOne {
Leave a break line between each class declaration.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +  {
The `{` should be in the upper line after `eventFade()`

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +  function reloadPage(){
Remember to leave an space between `()` and `{`

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Check indentation.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Check indentation.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Check indentation.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Check indentation.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Check indentation.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Check indentation.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Check indentation.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Check indentation.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +  xhttp.open('GET', config.url , true);
HTTP method could be a parameter inside config too.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +function eventRequestReusable(config, resolve, reject) {
Try to find a more descriptive name for the function. Like ajaxCall or something like this style.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/exerciseJS.js
> +  var xhttp = new XMLHttpRequest();
Check indentation.

2016-10-13 20:51 UTC, afiorenza commented on 01-JS-DOM-APIs/index.html
> +   </head>
Check indentation

2016-10-13 21:05 UTC, maurim96 commented on 01-JS-DOM-APIs/exercise12.html
> +   </head>
done

2016-10-13 21:05 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exercise12.html
> +      <th class="tableTH">Firstname</th>
done

2016-10-13 21:07 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exercise12.html
> +  <button onclick="importMatrixToDOM(matrix)" id="importMatrixButton" type="buttonImportMatrix" name="buttonImportMatrix">Import</button>
I confused this property(type) with this one 'name'. (was trying to named the button). Done

2016-10-13 21:09 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exercise12.js
> +    matrix = [
I already declared matrix on 'buttonHandler' (importMatrixToDOM). Done

2016-10-13 21:09 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exercise12.js
> +    console.log(matrix);
Done

2016-10-13 21:14 UTC, maurim96 commented on 01-JS-DOM-APIs/exercise12.js
> +      var trNode = document.createElement("tr");
Done. (i declared them like undefined (let 'variable';), i really don't know if thats right or if its better to declared them 'null' (object))

2016-10-13 21:15 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exercise12.js
> +      document.getElementById("dataTable").appendChild(trNode);
Done

2016-10-13 21:15 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.css
> +    width: 100%;
Done

2016-10-13 21:15 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.css
> +.hiddenOne {
Done

2016-10-13 21:17 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +  function reloadPage(){
Done

2016-10-13 21:17 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +  {
Done

2016-10-13 21:21 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Done

2016-10-13 21:21 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Done

2016-10-13 21:21 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Done

2016-10-13 21:21 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Done

2016-10-13 21:21 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Done

2016-10-13 21:21 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Done

2016-10-13 21:21 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +};
Done

2016-10-13 21:22 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +  var xhttp = new XMLHttpRequest();
Done

2016-10-13 21:23 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +function eventRequestReusable(config, resolve, reject) {
Done

2016-10-13 21:23 UTC, mauriciogbl commented on 01-JS-DOM-APIs/index.html
> +   </head>
Done

2016-10-13 21:25 UTC, mauriciogbl commented on 01-JS-DOM-APIs/index.html
> +   </head>
I checked and corrected every indentation problem, but now i'm not sure if it's right or i'm wrong about indentation standar.

2016-10-13 21:27 UTC, mauriciogbl commented on 01-JS-DOM-APIs/exerciseJS.js
> +  xhttp.open('GET', config.url , true);
Pending (i'll check it tomorrow)

2016-10-14 14:13 UTC, afiorenza approved these changes

2016-10-14 14:13 UTC, afiorenza commented
Ready for merge!

2016-10-14 17:17 UTC, merged